compilers:
  - name: Visual Studio
    version: 12
    cmake_extra_flags: -DBUILD_SHARED_LIBS:BOOL=OFF -DBUILD_PAT:BOOL=OFF -DBUILD_PACKAGE:BOOL=ON -DBUILD_TESTING:BOOL=ON -DBUILD_BOOST:BOOL=OFF -DBUILD_QT:BOOL=OFF -DBUILD_RUBY:BOOL=OFF -DBUILD_OPENSTUDIO_GEMS:BOOL=OFF -DUSE_PCH:BOOL=ON -DBUILD_CSHARP_BINDINGS:BOOL=ON -DMAXIMIZE_CPU_USAGE:BOOL=ON
  - name: Visual Studio
    version: 12
    architecture: Win64
    cmake_extra_flags: -DBUILD_SHARED_LIBS:BOOL=OFF -DBUILD_PAT:BOOL=OFF -DBUILD_PACKAGE:BOOL=ON -DBUILD_TESTING:BOOL=ON -DBUILD_BOOST:BOOL=OFF -DBUILD_QT:BOOL=OFF -DBUILD_RUBY:BOOL=OFF -DBUILD_OPENSTUDIO_GEMS:BOOL=OFF -DUSE_PCH:BOOL=ON -DBUILD_CSHARP_BINDINGS:BOOL=ON -DMAXIMIZE_CPU_USAGE:BOOL=ON


